export { default as Splash } from "./Splash";
export { default as MenuItem, MenuItemDIY } from "./MenuItem.js";
export { default as Main } from "./Main.js";
export { default as List1, ListDIY } from "./List.js";
export { default as Details } from "./Details";
export { default as DetailsMovie } from "./DetailsMovie";
export { default as TVDetails } from "./TVShows/TVDetails";
export { default as Simple } from "./Simple";
export { default as Sports } from "./Sports.js";
export { default as Movies } from "./Movies";
export { default as Tv } from "./TVShows/Tv";
export { default as Premium } from "./Premium";
export { default as WishList } from "./WishList";
export { default as Profile } from "./Profile";
export { default as UserProfile } from "./UserProfile";
export { default as EditProfile } from "./EditProfile/EditProfile";
export { default as Settings } from "./Settings/Settings";
export { default as ChangeAvatar } from "./EditProfile/ChangeAvatar";
export { default as Parental } from "./EditProfile/Parental/Parental";
export { default as VarifyPin } from "./EditProfile/VarifyPin/VarifyPin";
